import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // 1. Change Import style

export const generateLegalReport = (caseData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // --- HEADER ---
  doc.setFontSize(22);
  doc.text("FORENSIC AI ANALYSIS REPORT", pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by EchoTrace Engine | Case ID: ${caseData.caseId}`, pageWidth / 2, 28, { align: 'center' });
  
  doc.setDrawColor(0);
  doc.line(10, 32, pageWidth - 10, 32);

  // --- INTEGRITY SECTION ---
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("1. MEDIA INTEGRITY CERTIFICATION", 14, 45);
  
  const integrityColor = caseData.integrityStatus === 'VERIFIED_AUTHENTIC' ? [0, 128, 0] : [255, 0, 0];
  doc.setTextColor(...integrityColor);
  doc.setFontSize(12);
  doc.text(`STATUS: ${caseData.integrityStatus}`, 14, 52);
  doc.text(`CONFIDENCE SCORE: ${caseData.integrityScore}%`, 14, 58);
  
  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.text("Biometric analysis confirms identity match with provided ID. No generative AI artifacts detected.", 14, 65);

  // --- EXECUTIVE SUMMARY ---
  doc.setFontSize(14);
  doc.text("2. EXECUTIVE SUMMARY OF CONTRADICTIONS", 14, 80);
  
  const contradictions = caseData.contradictions.map(c => [
    c.severity,
    c.claim,
    c.evidence
  ]);

  // 2. USE 'autoTable(doc, options)' INSTEAD OF 'doc.autoTable'
  autoTable(doc, {
    startY: 85,
    head: [['Severity', 'Suspect Claim', 'Contradicting Evidence']],
    body: contradictions,
    headStyles: { fillColor: [41, 128, 185] },
    theme: 'grid'
  });

  // --- DETAILED TIMELINE ---
  // 3. Get the final Y position correctly from the last table
  const finalY = doc.lastAutoTable.finalY || 85;
  
  doc.setFontSize(14);
  doc.text("3. CHRONOLOGICAL RECONSTRUCTION", 14, finalY + 15);

  const timeline = caseData.timeline.map(t => [
    t.time,
    t.source,
    t.event
  ]);

  autoTable(doc, {
    startY: finalY + 20,
    head: [['Timestamp', 'Source', 'Event Description']],
    body: timeline,
    theme: 'striped'
  });

  // --- FOOTER ---
  const today = new Date().toLocaleDateString();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Report Generated: ${today} | This document is an algorithmic summary for investigative aid only.`, 14, 280);

  // Save File
  doc.save(`EchoTrace_Report_${caseData.caseId}.pdf`);
};