import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateLegalReport = (caseData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // --- HEADER ---
  doc.setFontSize(22);
  doc.text("FORENSIC AI ANALYSIS REPORT", pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by EchoTrace Engine | Case ID: ${caseData.caseId || 'REF-X72'}`, pageWidth / 2, 28, { align: 'center' });
  doc.line(10, 32, pageWidth - 10, 32);

  // --- 1. MEDIA INTEGRITY (AI Generated) ---
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("1. MEDIA INTEGRITY CERTIFICATION", 14, 45);
  
  // Dynamic Color for Status
  const integrityColor = caseData.integrityStatus === 'VERIFIED_AUTHENTIC' ? [0, 128, 0] : [255, 0, 0];
  doc.setTextColor(...integrityColor);
  doc.setFontSize(12);
  doc.text(`STATUS: ${caseData.integrityStatus?.replace('_', ' ')}`, 14, 55);
  doc.text(`CONFIDENCE SCORE: ${caseData.integrityScore}%`, 14, 62);
  
  // 🆕 NEW: AI REASONING BLOCK
  doc.setTextColor(60);
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text("AI FORENSIC REASONING:", 14, 70);
  
  doc.setFont(undefined, 'normal');
  const reasoningText = caseData.integrityReasoning || "No specific anomalies detected.";
  // Split text to fit width (180mm)
  const splitReasoning = doc.splitTextToSize(reasoningText, 180);
  doc.text(splitReasoning, 14, 76);

  // --- 2. EXECUTIVE SUMMARY (Human Verified) ---
  // Calculate Y position based on how long the reasoning text was
  let currentY = 85 + (splitReasoning.length * 5); 

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("2. INVESTIGATOR VERIFIED FINDINGS", 14, currentY);
  
  const contradictions = caseData.contradictions.map(c => [
    c.status === 'VERIFIED' ? 'VERIFIED' : 'DETECTED',
    c.severity,
    c.claim,
    c.evidence
  ]);

  autoTable(doc, {
    startY: currentY + 5,
    head: [['Status', 'Severity', 'Suspect Claim', 'Contradicting Evidence']], 
    body: contradictions,
    headStyles: { fillColor: [41, 128, 185] },
    theme: 'grid',
    didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 0) {
            if (data.cell.raw === 'VERIFIED') {
                data.cell.styles.textColor = [0, 128, 0];
                data.cell.styles.fontStyle = 'bold';
            }
        }
    }
  });

  // --- 3. TIMELINE ---
  const finalY = doc.lastAutoTable.finalY || currentY + 20;
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("3. CHRONOLOGICAL RECONSTRUCTION", 14, finalY + 15);

  const timeline = caseData.timeline.map(t => [
    t.time,
    t.source,
    t.event
  ]);

  autoTable(doc, {
    startY: finalY + 20,
    head: [['Timestamp', 'Source', 'Event Description']],
    body: timeline,
    theme: 'striped'
  });

  // --- 4. SIGNATURE ---
  const finalY2 = doc.lastAutoTable.finalY;
  
  doc.setFontSize(10);
  doc.text("I hereby certify that I have reviewed the AI-generated findings above.", 14, finalY2 + 20);
  doc.line(14, finalY2 + 35, 100, finalY2 + 35);
  doc.text("Investigator Signature", 14, finalY2 + 40);
  
  const today = new Date().toLocaleDateString();
  doc.text(`Date: ${today}`, 120, finalY2 + 40);

  doc.save(`EchoTrace_Report_${caseData.caseId}.pdf`);
};